#!/bin/bash

export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"

if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
 curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR
else
 php $OPENSHIFT_DATA_DIR/composer.phar self-update
fi

mkdir $OPENSHIFT_HOMEDIR/$VIGILANTUS_PUBLIC_FOLDER/brasao
chmod 777 $OPENSHIFT_HOMEDIR/$VIGILANTUS_PUBLIC_FOLDER/brasao

( unset GIT_DIR ; cd $OPENSHIFT_REPO_DIR ; php $OPENSHIFT_DATA_DIR/composer.phar require "fxp/composer-asset-plugin:1.0.*@dev"; php $OPENSHIFT_DATA_DIR/composer.phar install )
