version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-vigilantus}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
