version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
      - gearman

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vigilantus
      POSTGRES_USER: vigilantus
      POSTGRES_PASSWORD: vigilantus
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  gearman:
    image: artefactual/gearmand:latest
    ports:
      - "4730:4730"
